import React from 'react';
import './about.css'
const About = () => {
    return (
        <div className='container' style={{ textAlign: 'justify' }}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus assumenda, quaerat veniam exercitationem minus corporis, quae deserunt in dolorum qui a magni modi reprehenderit sit repellendus accusantium odit facilis porro.
                Qui, alias, recusandae soluta voluptas nihil, quia rem fuga deleniti repellendus fugit architecto? Reprehenderit dolorem amet, sunt hic eum, quasi pariatur minus laborum facere, fugit eveniet qui cupiditate obcaecati a.
                Mollitia voluptas adipisci, voluptates quibusdam quod praesentium alias cum porro fugiat neque quae, harum dolores commodi quisquam in debitis optio nemo labore, dolore enim maxime? Veritatis voluptas reprehenderit consequatur provident!
                Voluptatum ipsa suscipit placeat minus officia recusandae eaque incidunt, dolor dolorum similique vitae perspiciatis, adipisci deserunt assumenda quos provident iste aliquam, nemo cupiditate fuga inventore delectus! Animi odit rerum nihil?
                Similique, cum suscipit ut quasi consectetur eum exercitationem voluptates omnis maiores aut dolorem beatae quidem totam dolorum porro. Eum aperiam ut dolore repellat a molestias laudantium aliquid sed esse harum?
                Eius, sunt quasi. Vero, soluta alias consequatur culpa natus beatae fugit amet, magnam odit, neque quaerat officia iste aliquid. Obcaecati numquam blanditiis repellendus consectetur modi autem nobis neque non deleniti.
                Doloribus, eveniet rerum! Nulla assumenda quos totam deserunt, amet ipsam autem. Maxime hic sed tempora velit laudantium veniam assumenda exercitationem quas eveniet impedit distinctio sapiente, eum quaerat tempore. Vero, eos?
                Velit, nulla eveniet iusto, praesentium voluptate eum nemo nobis, officiis quo nisi similique natus saepe obcaecati. Doloremque repellendus dolores at incidunt nam quisquam praesentium accusamus. Possimus at saepe aspernatur? Eaque.
                Quidem ex eveniet ad facere temporibus, consectetur culpa perspiciatis incidunt dolorum maiores maxime aperiam, corporis odio quis laborum quas rem dicta provident. Reiciendis vel eveniet exercitationem id iusto at pariatur.
                Dolores consequatur magnam voluptatem aliquid illum vero, quibusdam sit veniam doloremque numquam natus minima. Voluptatem adipisci eveniet, fugiat laborum cumque debitis fugit porro cum ipsa voluptates tempore repellendus velit aliquam.
                Soluta minus officiis quam, voluptas ducimus sapiente aliquid pariatur ea vitae, expedita accusantium, doloremque excepturi impedit molestias eveniet quas quo. Incidunt, minima! Sunt accusamus sed dignissimos numquam quis aspernatur nisi.
                Nihil commodi minima fuga incidunt, vero illum rerum laborum tempore consequuntur, eveniet similique cumque quia ab asperiores quaerat nulla ducimus? Soluta, earum blanditiis odio pariatur officia nesciunt est id sint?
                Vitae quas quaerat porro id cum expedita soluta ullam debitis blanditiis quos, nobis qui quam itaque nesciunt harum quis rem dolorem voluptatibus deserunt pariatur laborum? Quas vel sit recusandae corrupti.
                Deserunt repellat officia nostrum explicabo ratione magnam quaerat deleniti? Nisi, impedit vero a dolores accusamus quaerat officiis sint. Dolores fugit eaque inventore blanditiis ad earum adipisci? Vero architecto excepturi libero?
                Tempora laborum nisi iusto ullam! Vitae temporibus sint facilis consequuntur minus voluptate, harum architecto consectetur, mollitia esse nihil? Velit fuga labore vero aperiam quos ipsam molestias odio assumenda architecto! Maxime!
                Ex dolorum optio a odio sed dolor vitae itaque debitis explicabo consequatur, aliquam laudantium quos, iste nobis fuga enim ad quibusdam inventore vel totam officiis modi maxime accusantium blanditiis? Consequuntur.
                Tempora laboriosam velit architecto, consectetur nostrum numquam consequatur rem, voluptatibus porro explicabo corporis odit praesentium ea repellendus, deserunt non alias illum minus maxime? Debitis, ullam? Suscipit minima quaerat ratione inventore!
                Fugit accusamus quaerat repellat similique modi fuga a. Maxime nostrum consequuntur fugit laborum iure! Modi totam quos deleniti voluptate magni vitae mollitia qui! Fuga libero illo obcaecati deserunt! Sunt, pariatur.
                Dolorem minus dolore neque? Beatae ratione eligendi enim odio odit minus? Qui consequatur suscipit, nulla veniam harum quasi fugit veritatis, saepe alias, praesentium officiis! Obcaecati ipsam labore enim earum vero.
                Soluta quia excepturi, voluptatibus quam dolores autem? Molestias iste explicabo et repellendus commodi numquam saepe ipsam quae iure, quas, unde laborum voluptatum excepturi nobis vitae at! Ratione reiciendis libero nam?
                Eum architecto placeat dolorum recusandae, veniam velit vel? Amet tempora magnam aliquam aperiam debitis illo et iusto minus rem sint asperiores praesentium esse, cupiditate, earum soluta inventore maiores impedit iste.
                Possimus exercitationem sint voluptatum sunt ea impedit labore tempore delectus quasi voluptatibus ab ipsam porro aliquam, iste architecto provident deleniti cum quo dolore atque, illum, eaque enim? Quam, commodi quasi?
                Nesciunt nobis quisquam tenetur non, atque aspernatur itaque quo sed obcaecati eaque enim necessitatibus dolorum, repellendus similique repudiandae reiciendis ab deleniti impedit totam ut quae, molestiae ratione? Delectus, accusantium iure.
                Maiores reiciendis quaerat tempore fuga incidunt commodi, repellat officia, debitis in obcaecati magnam blanditiis necessitatibus veniam provident deserunt repellendus? Praesentium, ea fugiat nostrum harum asperiores rerum vero! Amet, accusantium cupiditate!
                Tenetur ipsam ex voluptatum, reprehenderit earum repellat temporibus beatae ullam perferendis minus porro quasi nemo cum adipisci est illum molestias velit sed suscipit praesentium vero repellendus? Libero accusamus dolorum quisquam.
                Error cupiditate consectetur explicabo est hic neque possimus quos eaque id, maiores magni, corporis quisquam dolorem! Voluptas iure aperiam illo, aut voluptatem sunt placeat qui blanditiis hic ab modi atque.
                Quisquam magni, libero quidem nihil veritatis molestiae delectus, eius modi et laudantium tempore aut officia sapiente assumenda necessitatibus cupiditate, dolorem impedit. Necessitatibus ipsam odit atque! Nihil quo provident officiis voluptatum.
                Modi, quasi fugiat voluptates necessitatibus blanditiis vero quisquam aliquid autem dicta tempora aut obcaecati expedita accusamus quaerat maiores dignissimos nisi nam mollitia! Debitis voluptate voluptatem nobis, quas provident at nihil!
                Quam aperiam eligendi velit eaque libero repudiandae eius, quas, id voluptates doloremque ratione! Saepe pariatur nesciunt eligendi nam corporis officiis labore dolore est recusandae vitae. Nisi accusamus error impedit voluptates?
                Asperiores placeat repellat magnam! Nostrum magnam debitis animi dolor quasi quisquam nam hic perspiciatis commodi. Facilis libero non neque quasi, officiis saepe? Provident hic eius impedit consectetur saepe ut temporibus.
                Molestias illo expedita blanditiis qui, dolores labore quibusdam tempore quas ducimus doloribus asperiores ad et aperiam accusantium itaque neque dignissimos voluptas quos! Cumque ratione ducimus error nulla, at nobis provident.
                Modi autem voluptas, perferendis tenetur laudantium vero impedit consectetur pariatur possimus earum molestiae repellendus sunt, minima doloribus soluta aspernatur quis optio quam, voluptate sint fugiat maxime fugit non. Expedita, veritatis.
                Error sunt quia debitis quos. Optio eligendi illo at animi voluptate officiis dicta? Delectus hic quod dolorum? Quisquam consequatur, quas illo illum repudiandae labore deleniti quod saepe accusantium consectetur libero.
                Pariatur nihil beatae deserunt deleniti repudiandae at doloremque maiores vitae enim alias, voluptas dolor eaque quisquam inventore doloribus magnam voluptate porro expedita earum perferendis necessitatibus voluptatibus! In nemo dignissimos debitis!
                Exercitationem eveniet minus alias cupiditate expedita itaque laboriosam saepe ipsam doloremque eum facilis ducimus autem veritatis vel, molestias laudantium corporis voluptas modi! Nobis aut nihil quam placeat commodi labore aliquam.
                Blanditiis, quaerat nihil et, accusamus iusto dolore, atque eveniet provident molestiae sint rem? Consequuntur ipsum vero sequi consequatur, saepe inventore asperiores necessitatibus architecto repellat ipsam sapiente minus deleniti. Voluptatum, repellat.
                Magnam, repudiandae! At, non? Dolores molestias consectetur sed, natus perferendis eum ab atque vitae similique at nostrum accusantium nobis quas consequuntur earum modi eius aut. Explicabo quidem quas cumque autem!
                Voluptatem delectus iste quo quos numquam vel natus fugiat libero tempore non assumenda eaque labore, molestiae nesciunt saepe nemo error quam in minima ea, dolore a consequatur nulla? Omnis, doloremque!
                Excepturi, ipsam expedita. Laboriosam delectus sapiente recusandae, numquam magnam corporis possimus exercitationem non fugit beatae voluptates cupiditate commodi, modi rerum, aperiam nulla id alias doloremque incidunt reiciendis in! Eligendi, magni!
                Repudiandae ullam repellendus aliquam odio natus quidem quia quae asperiores eaque ab architecto consequatur cum, veniam optio numquam porro sapiente, perspiciatis vitae ratione veritatis. Provident molestiae numquam enim tempore deleniti?
                Ex ratione, placeat necessitatibus sint ea voluptatem commodi accusamus doloremque repellendus rerum tenetur itaque impedit quidem officia, quaerat obcaecati molestias voluptates nam corporis at! Expedita repudiandae ducimus sunt maxime ea.
                Deleniti ipsa at, expedita cupiditate modi reiciendis quibusdam? Tenetur nostrum quae a placeat optio esse eius eos doloremque. Et aperiam tenetur distinctio veniam voluptas tempora perferendis, hic quibusdam corporis labore?
                Inventore eius, odio itaque vel animi tempora. Qui, eum eius officia asperiores atque quos excepturi deleniti aliquid non, laboriosam mollitia incidunt harum voluptate reprehenderit numquam odio placeat magni accusantium consequuntur.
                Quod sed cupiditate rerum veniam debitis ducimus a, hic doloremque, esse laudantium maxime animi officia. Voluptas, consectetur saepe. Quas odit dolorem ratione reprehenderit accusantium corporis iste doloremque deserunt laudantium impedit!
                Impedit, necessitatibus dolores dolore voluptas, temporibus, quibusdam laboriosam aliquam voluptatem corporis ea quam quia debitis labore in voluptatibus! Consequuntur facere soluta cumque error beatae similique necessitatibus voluptate amet ipsa quod.
                Voluptate quod quam, molestias consequuntur odio suscipit eveniet pariatur tempore explicabo at rem provident alias facere beatae ab eius quo sint velit et repudiandae expedita asperiores nam. Aliquam, perferendis. Odio.
                Ipsam est repellendus hic quam minus quod reprehenderit, nemo at dolorem incidunt dolores dolor reiciendis. Ab quis architecto voluptas, dolores quidem, doloribus quo quae maxime sapiente quam voluptatibus quod officia.
                Temporibus similique iure at quasi voluptatibus vero adipisci quia odit impedit maiores repudiandae qui nihil, ex labore dolorem distinctio, deleniti repellendus! Aut dolorem tenetur explicabo odio, consequuntur optio vitae neque.
                Temporibus, quae facilis. Quas ducimus, voluptate nihil corrupti voluptas facere in minima! Totam assumenda magni, optio eius sit ab repudiandae quam expedita nulla magnam cupiditate velit, nesciunt quas. Asperiores, deserunt.
                Alias expedita cum totam rem eum exercitationem iste necessitatibus, ea dicta cupiditate magni facere vitae repellendus ducimus, aliquam minus a consequatur! Deleniti, mollitia dolore! Perspiciatis aut quidem sed placeat vel.</p>
        </div>
    );
}

export default About;
